### ISSUE TITLE
Fails to build the site with error ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by yznima** [djungelorm/sphinx-tabs#44]
I have sphinx site and I followed the documentation to install and add the sphinx_tabs to the conf.py. However I get the following error when trying to build again.

```
# Sphinx version: 2.0.1
# Python version: 3.7.0 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:
#   checking consistency...
#   
#   done
#   
#   preparing documents...
#   
#   done
#   
#   writing output... [  1%] README
#   
# Loaded extensions:
#   sphinx.ext.mathjax (2.0.1) from /usr/local/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from /usr/local/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /usr/local/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /usr/local/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from /usr/local/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /usr/local/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/local/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.graphviz (2.0.1) from /usr/local/lib/python3.7/site-packages/sphinx/ext/graphviz.py
#   sphinxcontrib.mermaid (2.0.1) from /usr/local/lib/python3.7/site-packages/sphinxcontrib/mermaid.py
#   recommonmark (0.5.0) from /usr/local/lib/python3.7/site-packages/recommonmark/__init__.py
#   sphinx_tabs.tabs (unknown version) from /usr/local/lib/python3.7/site-packages/sphinx_tabs/tabs.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.7/site-packages/sphinx/application.py", line 337, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 326, in build_update
    len(to_build))
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 389, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 569, in write
    self._write_serial(sorted(docnames))
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 580, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/html.py", line 650, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/usr/local/lib/python3.7/site-packages/sphinx/builders/html.py", line 1085, in handle_page
    templatename, ctx, event_arg)
  File "/usr/local/lib/python3.7/site-packages/sphinx/application.py", line 450, in emit_firstresult
    return self.events.emit_firstresult(event, self, *args)
  File "/usr/local/lib/python3.7/site-packages/sphinx/events.py", line 81, in emit_firstresult
    for result in self.emit(name, *args):
  File "/usr/local/lib/python3.7/site-packages/sphinx/events.py", line 76, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python3.7/site-packages/sphinx_tabs/tabs.py", line 281, in update_context
    context['css_files'].remove(path)
ValueError: list.remove(x): x not in list
```

**Comment by yznima** [comment]
@djungelorm Thanks for fixing this. Are you planning to release a new version as well?
