### ISSUE TITLE
Could it be possible to include the requirements (CSS/JS) only on pages using the extension?

### ISSUE THREAD

**Issue by Naereen** [djungelorm/sphinx-tabs#6]
Could it be possible to include the requirements (CSS/JS) only on pages using the `sphinx-tabs` extension ?

**Comment by Naereen** [comment]
Instead of including them on the header part of all pages (by adding a few lines to the default template), they could be included at the beginning of the first line of HTML body using the tabs?

**Comment by djungelorm** [comment]
Added. Thanks for the request!

**Comment by Naereen** [comment]
I will test it right now, thanks and :clap: for the clean code!

**Comment by Naereen** [comment]
I `git clone`d the repo, `sudo python3 setup.py install`ed it, but it doesn't look like it has changed.

Has your `test/other.rst` page worked for you?

**Comment by Naereen** [comment]
(See http://perso.crans.org/besson/sphinxtabs.en.html or http://perso.crans.org/besson/projects.en.html, no difference in the header)

**Comment by djungelorm** [comment]
Odd. When I build it by running `make test` using the makefile in the root of the project I see the following output:
https://gist.github.com/djungelorm/1fb8f79d3b450278b0ff2161050a4531

**Comment by Naereen** [comment]
OK, I should have forced the install to overwrite the files, sorry.

**Comment by djungelorm** [comment]
No worries. So you got it working then? The source at those two links you sent still look the same to me...

**Comment by Naereen** [comment]
I got this error:
```python
Not copying tabs assets! Error occurred previously

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.5/dist-packages/sphinx/builders/__init__.py", line 328, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python3.5/dist-packages/sphinx/builders/__init__.py", line 394, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/builders/__init__.py", line 431, in write
    self._write_serial(sorted(docnames))
  File "/usr/local/lib/python3.5/dist-packages/sphinx/builders/__init__.py", line 440, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/builders/html.py", line 561, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/builders/html.py", line 940, in handle_page
    templatename, ctx, event_arg)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 493, in emit_firstresult
    return self.events.emit_firstresult(event, self, *args)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/events.py", line 84, in emit_firstresult
    for result in self.emit(name, *args):
  File "/usr/local/lib/python3.5/dist-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python3.5/dist-packages/sphinx_tabs-0.2.2-py3.5.egg/sphinx_tabs/tabs.py", line 214, in add_assets
    context['css_files'].remove(path)
ValueError: list.remove(x): x not in list

Exception occurred:
  File "/usr/local/lib/python3.5/dist-packages/sphinx_tabs-0.2.2-py3.5.egg/sphinx_tabs/tabs.py", line 214, in add_assets
    context['css_files'].remove(path)
ValueError: list.remove(x): x not in list
```
See https://github.com/djungelorm/sphinx-tabs/commit/46c95806874926dc3c96ace45e6a847a96bdb500#commitcomment-22657416

**Comment by djungelorm** [comment]
Oops! Fixed and added a test. Does it work for you now?

**Comment by Naereen** [comment]
OK, with a manual hack to also remove the possible exception `TypeError: list indices must be integers or slices, not str` on [line 189](https://github.com/djungelorm/sphinx-tabs/blob/master/sphinx_tabs/tabs.py#L189), it worked.

:tada: !

**Comment by Naereen** [comment]
I think it will be good now. You can update it on Pypi when you want, IMO.
