### ISSUE TITLE
KeyError: 'css_files'

### ISSUE THREAD

**Issue by Twinters007** [djungelorm/sphinx-tabs#7]
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/frc-pdr/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 296, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/frc-pdr/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 333, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/frc-pdr/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/frc-pdr/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 322, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/frc-pdr/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 360, in write
    self._write_serial(sorted(docnames), warnings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/frc-pdr/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 368, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/frc-pdr/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 461, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/frc-pdr/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 1139, in handle_page
    self.app.emit('html-page-context', pagename, templatename, ctx, event_arg)
  File "/home/docs/checkouts/readthedocs.org/user_builds/frc-pdr/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 589, in emit
    results.append(callback(self, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/frc-pdr/envs/latest/local/lib/python2.7/site-packages/sphinx_tabs/tabs.py", line 215, in add_assets
    if path in context['css_files']:
KeyError: 'css_files'
```

**Comment by Twinters007** [comment]
Simple `if 'css_files' not in context: continue` should fix, but it seems you're trying to remove the path from context['css_files'], but that key is only populated if there are css files in that one page, yet the path includes *all* pages

**Comment by djungelorm** [comment]
Thanks for reporting this! I've committed some changes that should fix this.

**Comment by Twinters007** [comment]
When will we see them in a release?

**Comment by djungelorm** [comment]
I will do it now ;)

**Comment by djungelorm** [comment]
It's up on pypi
